// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Gn_46CTQMrT2QliXzV15Jk7GuyCXUwk',
    appId: '1:862937413785:web:a68ce9ae8a162eb9e66008',
    messagingSenderId: '862937413785',
    projectId: 'gdsc-t30',
    authDomain: 'gdsc-t30.firebaseapp.com',
    storageBucket: 'gdsc-t30.appspot.com',
    measurementId: 'G-XMLNDQB337',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAagY7iaCtLAnPR2RpUK9cOHjULrUnWZRg',
    appId: '1:862937413785:android:053bfc2a98907654e66008',
    messagingSenderId: '862937413785',
    projectId: 'gdsc-t30',
    storageBucket: 'gdsc-t30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKqW8jiGmgpmZ7nrQ-fWAhk2odgnqVc_o',
    appId: '1:862937413785:ios:433945df7ac29a4de66008',
    messagingSenderId: '862937413785',
    projectId: 'gdsc-t30',
    storageBucket: 'gdsc-t30.appspot.com',
    iosBundleId: 'com.example.protestProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKqW8jiGmgpmZ7nrQ-fWAhk2odgnqVc_o',
    appId: '1:862937413785:ios:6a4d61ab26014bd7e66008',
    messagingSenderId: '862937413785',
    projectId: 'gdsc-t30',
    storageBucket: 'gdsc-t30.appspot.com',
    iosBundleId: 'com.example.protestProject.RunnerTests',
  );
}
